[2019-12-05 23:33:43] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:184)
[stacktrace]
#0 /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(118): Illuminate\\Log\\LogManager->resolve(NULL)
#1 /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(98): Illuminate\\Log\\LogManager->get(NULL)
#2 /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(539): Illuminate\\Log\\LogManager->driver()
#3 /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(118): Illuminate\\Log\\LogManager->error('Undefined const...', Array)
#4 /var/www/html/PFC/app/Exceptions/Handler.php(37): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#5 /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#6 /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#7 /var/www/html/PFC/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#8 {main}
"} 
[2019-12-05 23:33:43] laravel.ERROR: Undefined constant 'App\Usuario' {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Undefined constant 'App\\Usuario' at /var/www/html/PFC/config/auth.php:71)
[stacktrace]
#0 /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php(72): require()
#1 /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Config\\Repository))
#2 /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(211): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap(Object(Illuminate\\Foundation\\Application))
#3 /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#4 /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#5 /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#6 /var/www/html/PFC/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#7 {main}
"} 
[2019-12-05 23:34:13] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:184)
[stacktrace]
#0 /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(118): Illuminate\\Log\\LogManager->resolve(NULL)
#1 /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(98): Illuminate\\Log\\LogManager->get(NULL)
#2 /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(539): Illuminate\\Log\\LogManager->driver()
#3 /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(118): Illuminate\\Log\\LogManager->error('Call to a membe...', Array)
#4 /var/www/html/PFC/app/Exceptions/Handler.php(37): Illuminate\\Foundation\\Exceptions\\Handler->report(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#5 /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#6 /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#7 /var/www/html/PFC/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#8 {main}
"} 
[2019-12-05 23:34:13] laravel.ERROR: Call to a member function connection() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function connection() on null at /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1253)
[stacktrace]
#0 /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1219): Illuminate\\Database\\Eloquent\\Model::resolveConnection(NULL)
#1 /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1051): Illuminate\\Database\\Eloquent\\Model->getConnection()
#2 /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(968): Illuminate\\Database\\Eloquent\\Model->newBaseQueryBuilder()
#3 /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1004): Illuminate\\Database\\Eloquent\\Model->newModelQuery()
#4 /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(957): Illuminate\\Database\\Eloquent\\Model->newQueryWithoutScopes()
#5 /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(947): Illuminate\\Database\\Eloquent\\Model->newQuery()
#6 /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(461): Illuminate\\Database\\Eloquent\\Model::query()
#7 /var/www/html/PFC/config/auth.php(71): Illuminate\\Database\\Eloquent\\Model::all()
#8 /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php(72): require('/var/www/html/P...')
#9 /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Config\\Repository))
#10 /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(211): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap(Object(Illuminate\\Foundation\\Application))
#11 /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#12 /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#13 /var/www/html/PFC/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#14 /var/www/html/PFC/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#15 {main}
"} 
